name: CI Activities

on:
    push:
        branches: ["main"]
jobs:
    testing:
        runs-on: ubuntu-latest
        steps:
            - name: Echo Test
              run: |
                echo "Testing 1 2 3"
