name: CI Testing

on:
    push:
        branches: ["main"]
jobs:
    CI_Testing:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.12'
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                pip install unittest-xml-reporting
            - name: Run Unit Tests
              run: python -m xmlrunner discover -o junit/test-results.xml
            - name: Lint with Ruff
              run: |
                pip install ruff
                ruff --output-format=github .
              continue-on-error: true
            - name: Run Dependency-Check
              uses: dependency-check/Dependency-Check_Action@main
              id: Depcheck
              with:
                project: 'Liala'
                path: '.'
                format: 'HTML'
                out: 'reports' # this is the default, no need to specify unless you wish to override it
                args: >
                    --failOnCVSS 6
                    --enableExperimental
                    --log reports/dc_log.txt
            - name: Upload Test Results
              uses: actions/upload-artifact@master
              with:
                name: Report unit test and dependency-check results
                path: ${{github.workspace}}/reports
