name: CI Testing

on:
    push:
        branches: ["main"]
jobs:
    static_tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Unit Tests
              run: python -m unittest -v 
            - name: Dependency-Check
              uses: dependency-check/Dependency-Check_Action@main
              id: Depcheck
              with:
                project: 'Liala'
                path: '.'
                format: 'HTML'
                out: 'reports' # this is the default, no need to specify unless you wish to override it
                args: >
                    --failOnCVSS 6
                    --enableExperimental
                    --log reports/dc_log.txt
            - name: Upload Test Results
              uses: actions/upload-artifact@master
              with:
                name: Report unit test and dependency-check results
                path: ${{github.workspace}}/reports
