name: Dependency-Check

on:
    push:
        branches: ["main"]
jobs:
    depcheck_test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Run dependency-check
              uses: dependency-check/Dependency-Check_Action@main
              id: Depcheck
              with:
                project: 'Liala'
                path: '.'
                format: 'HTML'
                out: 'reports' # this is the default, no need to specify unless you wish to override it
                args: >
                    --failOnCVSS 7
                    --enableRetired
                    --log reports/dc_log.txt
            - name: Upload test results
              uses: actions/upload-artifact@master
              with:
                name: Report dependency-check results
                path: ${{github.workspace}}/reports
